### ISSUE TITLE
Kill dead packages:  il.org.spartan.collections, il.org.spartan.bench, il.org.spartan.java, 	

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#10]

**Comment by yossigil** [comment]
Please link to the commit

**Comment by nerya50** [comment]
done in [https://github.com/TechnionYP5779/team2/commit/d5ded4958a2a49aff5b737546857fdb256470142](url)

**Comment by nerya50** [comment]
Done in commit d5ded4958a2a49aff5b737546857fdb256470142
