### ISSUE TITLE
Assert.assertThat ->azzer.that // Globally

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#104]

**Comment by nerya50** [comment]
you accidentally changed the spartanizer settings in d59c9c8a1199f2e4678f9235d2aa3c85885d9e50
![image](https://user-images.githubusercontent.com/19494000/48802643-74d64e80-ed18-11e8-94a0-4f938c73cc16.png)
i have fixed it in 67eab4d697f1334f2539ff69b39f5501a7d8303e
