### ISSUE TITLE
Unit test for class PropositionPrettyPrinter

### ISSUE THREAD

**Issue by OmerGlick** [TechnionYP5779/team2#105]

**Comment by addirabasker** [comment]
@OmerGlick great coverage. I have some pointers:
1. Separate tests that have multiple azzert code lines to separate tests.

**Comment by OmerGlick** [comment]
> @OmerGlick great coverage!
> One pointer I have for you is that you should separate tests that have multiple azzert code lines to separate tests.
> ![image](https://user-images.githubusercontent.com/33811361/48801051-11e2b880-ed14-11e8-8615-ec1b375e5b6a.png)
> Fix it and tag me for another review.

Fixed it

**Comment by addirabasker** [comment]
@OmerGlick  great. Good Job!
