### ISSUE TITLE
config travis or maven so no test will be missed

### ISSUE THREAD

**Issue by neryac** [TechnionYP5779/team2#106]
travis is missing 98 tests 😢 
![image](https://user-images.githubusercontent.com/19494000/48736694-9d951000-ec54-11e8-84fd-728b6eddbc42.png)
![image](https://user-images.githubusercontent.com/19494000/48736804-f5cc1200-ec54-11e8-92ae-3aa8bfc0de58.png)

**Comment by nerya50** [comment]
the problem is in maven configuration and not travis
