### ISSUE TITLE
Unit test for class note

### ISSUE THREAD

**Issue by OmerGlick** [TechnionYP5779/team2#109]

**Comment by addirabasker** [comment]
@OmerGlick Great coverage!
I have some pointers:
1. Make sure the code is spartanized and **cleaned up**.
2. After you do that you'll find out that you dont need 'import fluent.ly.note.*;' in line 10 so **remove that**.
3. Are you certain that this is the best empty implementation for a function:
![image](https://user-images.githubusercontent.com/33811361/48852544-47d87900-edb6-11e8-8467-080aba9b5702.png)

**Comment by addirabasker** [comment]
@OmerGlick  Good job 👍
