### ISSUE TITLE
Research about project idea of ClassScheduling

### ISSUE THREAD

**Issue by DorKab** [TechnionYP5779/team2#129]
The ClassScheduling is a tool for matching teaching assistants to classrooms.
Research about this idea.

**Comment by GuySuday** [comment]
## ClassScheduling
Every semester, faculties need to schedule lecturers and TAs according to their personal preferences.
The problems start when 2 or more semester-recommended courses scheduled to the same hour, or to different hours, but the classes are very far from each other.
The goal is to schedule each course according to the staff's constraints, while considering the recommended courses, and the distance between close courses

### Input
* Courses hours
* Staff constraints
* Faculty catalog
### Output
Several options for scheduling all the courses on the catalog according to the constraints, while considering that different students take different courses taking place in different buildings

**Comment by nerya50** [comment]
abandoned
