### ISSUE TITLE
Research about project idea of ForkIt

### ISSUE THREAD

**Issue by DorKab** [TechnionYP5779/team2#131]

**Comment by addirabasker** [comment]
ForkIt is a tool to help the user decide what meal to eat at the restaurant he /she decides to eat in.
The user would enter the amount of money he/she is willing to spend on the meal and the user's preferences and the output will be the different variations for appetizer,  entree, dessert and drinks. based on the restaurant's menu. 
Furthermore, the tool will allow customization such as how to split the Bill for example.
Research about this idea.

**Comment by nerya50** [comment]
abandoned

**Comment by GuySuday** [comment]
![image](https://user-images.githubusercontent.com/19148420/50585230-ac3e2c00-0e7c-11e9-8c9f-e0764208b52c.png)

**Comment by GuySuday** [comment]
### Challenges:
* **Parsing a menu** - automatic (requires online menu, requires smart parser) OR manually ("hardcoded")
* **Building a recommendation algorithm** - AI OR weighted parameters(e.g: popular dish, likes...). Either way, requires a lot of data
* **Dish labels** - how specific will they be?
* **Representing a dish** - ingredients + labels
