### ISSUE TITLE
Create interface DateTime

### ISSUE THREAD

**Issue by OmerGlick** [TechnionYP5779/team2#153]
- [ ] getDate

- [ ] getDay

- [ ] getHour

- [ ] getMinute

**Comment by DorKab** [comment]
The name of this interface is NOT final!
Think of a better name that describes this interface.

**Comment by DorKab** [comment]
Do we really need the last 3 methods?
I think getDate should be enough, since it returns a java LocalDateTime object, from which we can extract everything we need.
