### ISSUE TITLE
Create interface Database

### ISSUE THREAD

**Issue by OmerGlick** [TechnionYP5779/team2#155]
- [x] getBuyer(Integer id)->Buyer

- [x] getSeller(Integer id)->Seller

- [x] getParkingSpot(Integer id)->ParkingSpot

- [x] add(Buyer)

- [x] add(Seller)

- [x] add(ParkingSpot)

- [x] removeBuyer(Integer id)

- [x] removeSeller(Integer id)

- [x] removeParkingSpot(Integer id)

- [x] update(Integer id, Buyer)

- [x] update(Integer id, Seller)

- [x] update(Integer id, ParkingSpot)

**Comment by DorKab** [comment]
name is NOT final.
