### ISSUE TITLE
Choose Database

### ISSUE THREAD

**Issue by DorKab** [TechnionYP5779/team2#158]

**Comment by nerya50** [comment]
for now we will work with firebase

**Comment by nerya50** [comment]
[**_Microsoft Azure_**](https://azure.microsoft.com/en-us/)
- as students, each of as has [100$](https://azure.microsoft.com/en-us/free/students/) credit to use. 
- big and stable service.
- fast and reliable.

**Comment by nerya50** [comment]
_**[Amazon Web Services (AWS)](https://aws.amazon.com/)**_
**pros:**
- as students we can got a free plain.
- big and stable service.
- fast and reliable.

**cons:**
- needs payment information to complete registration.
