### ISSUE TITLE
Unit tests for class Pair

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#16]

**Comment by nerya50** [comment]
@DorKab 
1.  insted of `assertEquals(a, b)` and `assertNotEquals(a, b)` use `azzert.that(a, is(b))` and `azzert.that(a, is(b))`
![image](https://user-images.githubusercontent.com/19494000/48634470-40882880-e9ce-11e8-9c6e-fca0b93146b6.png)

2. imrove code coverage

**Comment by DorKab** [comment]
@nerya50 Check again please

**Comment by nerya50** [comment]
checked
