### ISSUE TITLE
Unit tests for class Statistics

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#18]

**Comment by jsmm0202** [comment]
I'm having trouble running one of the functions for the test- prune. 
It seems like the import for 'Iterables' is problematic. 
Is there any chance that in  `import il.org.spatan.iteration.*;`, "spartan" is spelled wrong?
@yossigil, could you take a look please?

**Comment by yossigil** [comment]
thanks

**Comment by OmerGlick** [comment]
Reviewed. Good test unit, I just removed one unnecessary import from it to remove a warning
