### ISSUE TITLE
Implement Database interface

### ISSUE THREAD

**Issue by DorKab** [TechnionYP5779/team2#182]

**Comment by nerya50** [comment]
for firebase we need to use REST or Admin SDK.
for REST we can use [firebase4j](https://github.com/bane73/firebase4j)

**Comment by nerya50** [comment]
for now we will work with Azure.
The relevant tables were created.

**Comment by neryac** [comment]
2b111c7c8950f351ef25d47f1403a13f6215b412
eb77304829fcaedbbc37179efc658646f58ea733
0f587f5b59cc328c8f5957cacf317312d44def4e
5c8346d7e88245f95c87c343bbb7428605e53a66
49a1d3e7a5b329965bffa5f936943d07fcb65f81
452eaac0be5c0031984b85d4b08a2e5d03ac9789
c696ecbd0795a01b923d81a278bcbe137a9a5839
