### ISSUE TITLE
Unit tests for interface anonymous

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#22]

**Comment by nerya50** [comment]
@jsmm0202 
1. you missed the `static <T> T ly(final Supplier<T> $)` function in your tests.
![image](https://user-images.githubusercontent.com/19494000/48661115-abd90580-ea75-11e8-9179-1149f943ed6c.png)

2. `@Test public void tTest() ` is redundant, delete it.

**Comment by jsmm0202** [comment]
@nerya50 `tTest` was the test for `static <T> T ly(final Supplier<T> $)`, I guess it was changed by the Spartanizer and somehow ruined, I'll try to figure out what happened, thank you!

**Comment by jsmm0202** [comment]
@nerya50 I changed the code a little bit so each test only has one assert and fixed the problem you mentioned.
Check the code again and let me know if you think I need to change something else.

**Comment by nerya50** [comment]
great work
