### ISSUE TITLE
Unit tests for interface as

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#23]

**Comment by nerya50** [comment]
1. delete all commented code 
![image](https://user-images.githubusercontent.com/19494000/48621359-fa21d200-e9ab-11e8-8c96-c48902b9ed98.png)

2. use `azzert.that(a, is(b))` insted of `azzert.assertEquals(a, b)` or `azzert.zero(a)` and etc where posiable.
![image](https://user-images.githubusercontent.com/19494000/48621374-03ab3a00-e9ac-11e8-89ee-ff93cf09b4d3.png)

3. use static  import for Utils.
![image](https://user-images.githubusercontent.com/19494000/48621813-6fda6d80-e9ad-11e8-95cb-df9a3553eb19.png)

4.  use `box(int[] a)` insted `(box(a), box(b), box(c), ... )` where possiable.
![image](https://user-images.githubusercontent.com/19494000/48621908-c47de880-e9ad-11e8-8f61-4c0ae7d229c7.png)

**Comment by addirabasker** [comment]
@nerya50 
1. done - there are no more comments like that
2. done - changed some code line to more specific use of azzert
3. done
4. done
Please check the code again and close the issue if everything is alright now.

**Comment by nerya50** [comment]
ok
