### ISSUE TITLE
document interface forget and add unit tests

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#28]

**Comment by dormaayan** [comment]
@nerya50 You should explain what the purpose of the interface in the document is. All the idea is that the interface is empty, so test it does what we expect it to do (even if it is simple)

**Comment by DorKab** [comment]
> @nerya50 You should explain what the purpose of the interface in the document is. All the idea is that the interface is empty, so test it does what we expect it to do (even if it is simple)

@dormaayan Not sure what is the purpose of the interface. Is it about ignoring warnings on unused variables, or about ignoring exceptions, or maybe anything else?

**Comment by dormaayan** [comment]
I thnink it is pretty flexible and can be used for many purposes. There are few usage examples in the code

**Comment by yossigil** [comment]
use boxing class instead of , eg. Double.valueOf(1.19)
