### ISSUE TITLE
use tdd to define a class that defines a list of pairs of real numbers

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team2#47]
this list could be used e.g., for representing a set of data points to draw in an xy graph, 
e.g., x is time and y is weight. the series is the list of data points.

- [x]  function recod(x,y)
- [x] iteration over pairs sorted by
- [x] statistics, such as count of data points.
- [x] implement linear regression https://en.wikipedia.org/wiki/Simple_linear_regression

**Comment by jsmm0202** [comment]
While implementing this class using TDD I also implemented 3 helper classes.
So overall I implemented:
```
PairList.java
SortableDoublePair.java
LinearLine.java
LinearRegression.java
```
In `/fluent.ly/src/main/java/il/org/spartan/utils`
and
```
PairListTest.java
LinearLineTest.java
LinearRegressionTest.java
```
In `/fluent.ly/src/test/java/il/org/spartan/utils`.

Please review and close the issue or tell me if you think I need to change something :)

**Comment by nerya50** [comment]
some functions names were changed due to java naming convention during code smells clean up - #137.
reviewed.
