### ISSUE TITLE
remove blah.txt

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#48]
make sure all files on the repo are live

**Comment by nerya50** [comment]
@yossigil what does that mean "live file"?

**Comment by yossigil** [comment]
Issues ETA.csv

this is not a file you are going to update, are you?
better integerate it with a wiki page

**Comment by yossigil** [comment]
thanks

**Comment by nerya50** [comment]
commit 6a1ada21cb5be8717dd9eccd21b3827e50984b0c
