### ISSUE TITLE
install the spartanizer plugin in all team members

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#49]
you have 300 tips

**Comment by nerya50** [comment]
see https://github.com/SpartanRefactoring/Main/wiki/Installation-Instructions

**Comment by nerya50** [comment]
@GuySuday @jsmm0202 @talporat @addirabasker @DorKab @OmerGlick 
after you got the spartanizer plugin installed, just reply "DONE" here, so the last (7th) one could close this issue.

**Comment by nerya50** [comment]
DONE

**Comment by GuySuday** [comment]
DONE

**Comment by yossigil** [comment]
good job

**Comment by OmerGlick** [comment]
DONE

**Comment by DorKab** [comment]
DONE

**Comment by addirabasker** [comment]
DONE

**Comment by talporat** [comment]
DONE

**Comment by jsmm0202** [comment]
DONE
