### ISSUE TITLE
Read MetaTester article

### ISSUE THREAD

**Issue by GuySuday** [TechnionYP5779/team2#58]
Write 'DONE' when you finish to read. The last one will close the issue.

**Comment by OmerGlick** [comment]
DONE

**Comment by addirabasker** [comment]
DONE

**Comment by DorKab** [comment]
DONE

**Comment by GuySuday** [comment]
DONE

**Comment by talporat** [comment]
DONE

**Comment by jsmm0202** [comment]
DONE

**Comment by yossigil** [comment]
the last one was supposed to hit DONE

**Comment by jsmm0202** [comment]
@yossigil I was the last one, I wrote "DONE" and closed the issue

**Comment by GuySuday** [comment]
@yossigil 
This issue is only for reading. In the next meeting we will discuss this article alongside other proposed project's ideas

**Comment by nerya50** [comment]
> AND WHAT WAS THE DELIVERABLE? JUST READING? ??

for now, so we will be able to discuss about it at our next meeting.
