### ISSUE TITLE
consolidate function unused into interface forget

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team2#60]
_From @yossigil on November 14, 2018 9:14_

they do the same; refactor the code accordingly

_Copied from original issue: TechnionYP5779/team6#80_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#120

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#105

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#78

**Comment by DorKab** [comment]
@dormaayan what about #59?

**Comment by yossigil** [comment]
could be duplicate...

**Comment by yossigil** [comment]
is this closed?

**Comment by yossigil** [comment]
?

**Comment by yossigil** [comment]
Who is the reviewer?

**Comment by DorKab** [comment]
> Who is the reviewer?

I assigned @jsmm0202

**Comment by jsmm0202** [comment]
I think it's done
