### ISSUE TITLE
Check again that you do not use junit Assert, but only class azzert

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team2#61]
_From @yossigil on November 14, 2018 9:14_

You can do this manually, or write a script. it is up to you. 

_Copied from original issue: TechnionYP5779/team6#79_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#76

**Comment by yossigil** [comment]
tip: Maybe use Ctrl-Shift-G

**Comment by addirabasker** [comment]
![image](https://user-images.githubusercontent.com/33811361/48613736-3990f400-e995-11e8-83fc-4490d7c410c1.png)
