### ISSUE TITLE
Document a push procedure in a wiki page

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team2#62]
_From @yossigil on November 14, 2018 9:11_

Should include formatting, cleanup, tests, spartanization etc.

_Copied from original issue: TechnionYP5779/team6#78_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#122

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#107

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#80

**Comment by yossigil** [comment]
don't forget to ask people to reformat the code

**Comment by talporat** [comment]
https://github.com/TechnionYP5779/team2/wiki/Push-procedure
