### ISSUE TITLE
Reopen all non-trivial issues, and make sure that someone else closes them

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team2#64]
_From @yossigil on November 14, 2018 9:2_

in particular, if you closed an non-trivial issue, reopen it, and ask someone else in your team verifies that the issue can be closed.

_Copied from original issue: TechnionYP5779/team6#76_

**Comment by yossigil** [comment]
Please add a commit number for all issues that were closed without a commit number.
This is an exercise in searching git history

**Comment by nerya50** [comment]
reopend mine - #12, #25, #32, #33, #34, #36, #37 and #38.

**Comment by addirabasker** [comment]
reopened mine - #15 , #23

**Comment by GuySuday** [comment]
Reopened mine - #17, #27, #54, #76, #77

**Comment by jsmm0202** [comment]
Reopened mine - #18 #19

**Comment by talporat** [comment]
Reopened mine - #12,#20,#79

**Comment by OmerGlick** [comment]
Reopened #101, #97 , #14
