### ISSUE TITLE
Test runs should be with assertions enabled

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team2#66]
_From @yossigil on November 14, 2018 9:21_

Play with eclipse, it is better to write
`assert x`
then
`azzert.isTrue(x)`

but when you run tests the jvm should have assertions enabled

_Copied from original issue: TechnionYP5779/team6#82_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#81

**Comment by yossigil** [comment]
You should use a jvm flag. Can you please show where this flag is set? use screen dump if necessary

**Comment by nerya50** [comment]
![image](https://user-images.githubusercontent.com/19494000/48545216-0fc0ca00-e8ce-11e8-98fb-7e9d0a62f8e1.png)
![image](https://user-images.githubusercontent.com/19494000/48545290-41399580-e8ce-11e8-811b-5c4d0937cdf4.png)

**Comment by nerya50** [comment]
@GuySuday @jsmm0202 @talporat @DorKab @OmerGlick @addirabasker 
should be already enabled, just make sure of it.
comment DONE and the last one will close this issue.

**Comment by nerya50** [comment]
DONE

**Comment by GuySuday** [comment]
DONE

**Comment by OmerGlick** [comment]
DONE

**Comment by jsmm0202** [comment]
DONE

**Comment by addirabasker** [comment]
DONE

**Comment by DorKab** [comment]
DONE

**Comment by talporat** [comment]
DONE
