### ISSUE TITLE
Integrate github issues with eclipse

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team2#67]
_From @yossigil on November 14, 2018 9:24_

for this, you need a proper mylyn connector. Best done by one team member figruing this out, and then
letting him instruct other members.

in short, github issues should be shown in the eclipse task list view.

![image](https://user-images.githubusercontent.com/12775400/48472870-e174b900-e7ff-11e8-8357-cf6c77bd12c5.png)

this is what the end results looks like in my machine. I can even see this issue on my eclipse:

![image](https://user-images.githubusercontent.com/12775400/48473379-03bb0680-e801-11e8-99b9-64c5d470c03a.png)

_Copied from original issue: TechnionYP5779/team6#83_

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:26_

be sure to enter the github password to and save it in eclipse, otherwise, you will get errors in synching.

here is where you add the password

![image](https://user-images.githubusercontent.com/12775400/48473150-8c857280-e800-11e8-8b18-152753de853c.png)

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:30_

![image](https://user-images.githubusercontent.com/12775400/48473035-3dd7d880-e800-11e8-8753-e906d36a448d.png)

this is where you add repos.

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:37_

hint, do an internet search

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#127

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#82

**Comment by nerya50** [comment]
https://github.com/TechnionYP5779/team2/issues/49#issuecomment-436787087
You know the drill

**Comment by nerya50** [comment]
DONE

**Comment by nerya50** [comment]
step by step:
1. in the sub menu Help click on "Install New Software".
![image](https://user-images.githubusercontent.com/19494000/48496016-cc1c8080-e839-11e8-902d-876a70cf0a23.png)

2. in the pop up window chose Work with: --All Available Sites--
    search for "github" and mark the "Eclipse GitHub integration with task focused interface"
![image](https://user-images.githubusercontent.com/19494000/48496526-d9863a80-e83a-11e8-9182-28bdb50724c9.png)

3. click next
![image](https://user-images.githubusercontent.com/19494000/48496815-8496f400-e83b-11e8-8892-1537510feb6b.png)

4. chose accept and click next.
![image](https://user-images.githubusercontent.com/19494000/48496897-b314cf00-e83b-11e8-85dc-37ade81ac97f.png)

5. the eclipse will run the installation process. afterward, in the pop up window, chose restart now.
![image](https://user-images.githubusercontent.com/19494000/48497084-21599180-e83c-11e8-849b-be2cffe5978f.png)

6. after the eclipse will restart, in the sub menu window, under show view, click on Task List.
![image](https://user-images.githubusercontent.com/19494000/48497374-ad6bb900-e83c-11e8-85ec-9b2c54e8302d.png)

7. in the Task List view, click on the drop down button next to the new task button, and chose add repository.
![image](https://user-images.githubusercontent.com/19494000/48497550-08051500-e83d-11e8-9d84-53508fbb6948.png)

8. in the pop up window, chose github issues and click next.
![image](https://user-images.githubusercontent.com/19494000/48497665-4b5f8380-e83d-11e8-94b6-864d20e78eed.png)

9. type "https://github.com/TechnionYP5779/team2" in the server field, fill in your username and password. check the save password box, and click on validate settings. if success appears on window's top, click on finish.
![image](https://user-images.githubusercontent.com/19494000/48498302-a6de4100-e83e-11e8-9d30-f64db2150f85.png)

**Comment by nerya50** [comment]
in order to see the issues, you need to create queries.

1. in the Task List view, click on the drop down button next to the new task button, and chose new query.
![image](https://user-images.githubusercontent.com/19494000/48498821-b6aa5500-e83f-11e8-91a6-b5d39ec2badd.png)

2. in the pop up window chose TechnionYP5779/team2 issues and click next.
![image](https://user-images.githubusercontent.com/19494000/48499078-42bc7c80-e840-11e8-93f7-944a68b01df5.png)

3. set your query. for example, for the query Open which will show all the open issues, do:
        i) name your query Open.
        ii) check only the open box and make sure there is no other checked box (include labels boxes).
        iii) set milestone to none.
        iv) click finish.

![image](https://user-images.githubusercontent.com/19494000/48499692-ab582900-e841-11e8-9f71-07cc2035590a.png)

now your eclipse is integrated with github issues.
![image](https://user-images.githubusercontent.com/19494000/48499886-2b7e8e80-e842-11e8-8acd-0d86da7456de.png)

DONE.

**Comment by yossigil** [comment]
nice job

**Comment by GuySuday** [comment]
![image](https://user-images.githubusercontent.com/19148420/48546827-f6218180-e8d1-11e8-885e-f8826421cccc.png)
DONE

**Comment by addirabasker** [comment]
![image](https://user-images.githubusercontent.com/33811361/48558174-478d3900-e8f1-11e8-8e47-ed3fe6450191.png)
DONE

**Comment by OmerGlick** [comment]
![image](https://user-images.githubusercontent.com/44426591/48583670-5fd07880-e930-11e8-9073-4fad3a614aa6.png)

DONE

**Comment by jsmm0202** [comment]
![capture](https://user-images.githubusercontent.com/37835129/48600459-962fe700-e974-11e8-9e21-f395a881b65f.JPG)
DONE

**Comment by DorKab** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/44426581/48621870-9ef0df00-e9ad-11e8-809b-fcfaa05eb272.png">
DONE

**Comment by talporat** [comment]
![image](https://user-images.githubusercontent.com/27850098/48670070-c2d13380-eb19-11e8-9472-3cb289cadafe.png)

DONE
