### ISSUE TITLE
connect your project to SonarQube

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team2#68]
_From @yossigil on November 14, 2018 9:40_

for now, just connect. later we shall decide which rules to use.

_Copied from original issue: TechnionYP5779/team5#128_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#83

**Comment by GuySuday** [comment]
![image](https://user-images.githubusercontent.com/19148420/48641245-cfeb0700-e9e1-11e8-897c-0403604ece71.png)

Our project is connected to SonarQube

**Comment by yossigil** [comment]
link?

**Comment by nerya50** [comment]
https://sonarcloud.io/dashboard?id=il.org.spartan%3Afluent.ly.2
