### ISSUE TITLE
Change milestone "Sprint 0" to "Sprint-Zero"

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#78]
_From @yossigil on November 14, 2018 9:42_

milestones with spaces in them may confuse eclipse

_Copied from original issue: TechnionYP5779/team6#84_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team1#91

**Comment by nerya50** [comment]
DONE.
![image](https://user-images.githubusercontent.com/19494000/48517294-83cb8580-e86e-11e8-9f2b-9a4258222e4d.png)

**Comment by yossigil** [comment]
are you sure that you spartanized the code?

**Comment by nerya50** [comment]
@yossigil 
![image](https://user-images.githubusercontent.com/19494000/48517401-e1f86880-e86e-11e8-8464-319e3c56a772.png)
why?

**Comment by yossigil** [comment]
cause this helps eclipse, which gets confused by the space
