### ISSUE TITLE
add some more descriptive stuff in your readme.md file

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#81]
_From @yossigil on November 8, 2018 17:37_

remember this is how people will see you project on the web

_Copied from original issue: TechnionYP5779/team6#64_

**Comment by GuySuday** [comment]
Check if there is more information you would like to add to the README file, and update accordingly.
E.g: I added links via 66ac16bf07f758a3313bbacefb2cbc698f27fff4
